import axios from 'axios';
import { Client } from '@notionhq/client';

const NOTION_API_VERSION = '2022-06-28';

interface RoadmapTask {
  id: string;
  title: string;
  description: string;
  estimatedHours: number;
  resources?: string[];
  completed: boolean;
}

interface RoadmapMilestone {
  week: number;
  title: string;
  tasks: RoadmapTask[];
}

interface RoadmapData {
  duration: number;
  milestones: RoadmapMilestone[];
  projectSuggestions?: Array<{
    title: string;
    description: string;
    skills: string[];
    difficulty: string;
  }>;
  targetCompletionDate?: Date;
  estimatedHours?: number;
  weeklyCommitment?: string;
}

interface InterviewQuestion {
  question: string;
  type: 'technical' | 'behavioral' | 'system_design';
  expectedAnswer?: string;
  hints?: string[];
}

interface ExportResult {
  pageId: string;
  url: string;
}

// Helper function to create Notion client
function createNotionClient(accessToken: string): Client {
  return new Client({
    auth: accessToken,
  });
}

// Helper function to make Notion API requests
async function notionRequest(
  accessToken: string,
  endpoint: string,
  method: 'GET' | 'POST' | 'PATCH' = 'GET',
  data?: any
) {
  const url = `https://api.notion.com/v1${endpoint}`;
  
  try {
    const response = await axios({
      method,
      url,
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Notion-Version': NOTION_API_VERSION,
        'Content-Type': 'application/json',
      },
      data,
    });
    return response.data;
  } catch (error: any) {
    console.error('Notion API Error:', error.response?.data || error.message);
    throw error;
  }
}

// Search for existing pages or databases
export async function searchNotion(accessToken: string, query: string) {
  return notionRequest(accessToken, '/search', 'POST', { query });
}

// Create a new page in Notion
export async function createPage(
  accessToken: string,
  parentId: string,
  title: string,
  blocks: any[] = []
): Promise<ExportResult> {
  const data = {
    parent: { page_id: parentId },
    properties: {
      title: {
        title: [{ text: { content: title } }],
      },
    },
    children: blocks,
  };

  const response = await notionRequest(accessToken, '/pages', 'POST', data);
  
  return {
    pageId: response.id,
    url: response.url,
  };
}

// Export roadmap to Notion
export async function exportRoadmapToNotion(
  accessToken: string,
  assessment: any,
  roleName: string
): Promise<ExportResult> {
  const notion = createNotionClient(accessToken);
  
  // Search for existing GapSense page
  const searchResponse = await notion.search({ query: 'GapSense Roadmaps' });
  let parentPage = searchResponse.results.find((result: any) => 
    result.object === 'page' && 
    result.properties?.title?.title?.[0]?.plain_text === 'GapSense Roadmaps'
  ) as any;

  // Create parent page if it doesn't exist
  if (!parentPage) {
    // Use raw axios helper to send { workspace: true } — the SDK types don't include this variant
    parentPage = await notionRequest(accessToken, '/pages', 'POST', {
      parent: { workspace: true },
      properties: {
        title: {
          title: [{ text: { content: 'GapSense Roadmaps' } }],
        },
      },
    });
  }

  const roadmap: RoadmapData = assessment.roadmap;
  const completionDate = roadmap.targetCompletionDate 
    ? new Date(roadmap.targetCompletionDate).toLocaleDateString()
    : 'Not set';

  // Create blocks for the roadmap content
  const blocks: any[] = [
    {
      object: 'block',
      type: 'heading_1',
      heading_1: {
        rich_text: [{ text: { content: `📋 ${roleName} - 60-Day Learning Roadmap` } }],
      },
    },
    {
      object: 'block',
      type: 'paragraph',
      paragraph: {
        rich_text: [
          { text: { content: 'This roadmap was generated by GapSense AI based on your skills assessment.' } },
        ],
      },
    },
    {
      object: 'block',
      type: 'callout',
      callout: {
        rich_text: [
          { text: { content: `Duration: ${roadmap.duration} days | Target Completion: ${completionDate} | Estimated Hours: ${roadmap.estimatedHours || 'N/A'}` } },
        ],
        icon: { emoji: '📊' },
      },
    },
    {
      object: 'block',
      type: 'divider',
      divider: {},
    },
  ];

  // Add milestones
  for (const milestone of roadmap.milestones) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: [{ text: { content: `Week ${milestone.week}: ${milestone.title}` } }],
      },
    });

    for (const task of milestone.tasks) {
      blocks.push({
        object: 'block',
        type: 'to_do',
        to_do: {
          rich_text: [{ text: { content: `${task.title} (${task.estimatedHours}h)` } }],
          checked: task.completed,
        },
      });

      blocks.push({
        object: 'block',
        type: 'paragraph',
        paragraph: {
          rich_text: [{ text: { content: task.description } }],
          color: 'gray',
        },
      });

      // Add resources if available
      if (task.resources && task.resources.length > 0) {
        blocks.push({
          object: 'block',
          type: 'bulleted_list_item',
          bulleted_list_item: {
            rich_text: [
              { text: { content: 'Resources: ' } },
              ...task.resources.map((r: string, i: number) => ({
                text: { 
                  content: r,
                  link: r.startsWith('http') ? { url: r } : undefined
                },
              })),
            ],
          },
        });
      }
    }

    blocks.push({
      object: 'block',
      type: 'divider',
      divider: {},
    });
  }

  // Add project suggestions section
  if (roadmap.projectSuggestions && roadmap.projectSuggestions.length > 0) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: [{ text: { content: '🚀 Project Suggestions' } }],
      },
    });

    for (const project of roadmap.projectSuggestions) {
      blocks.push({
        object: 'block',
        type: 'toggle',
        toggle: {
          rich_text: [{ text: { content: `${project.title} (${project.difficulty})` } }],
          children: [
            {
              object: 'block',
              type: 'paragraph',
              paragraph: {
                rich_text: [{ text: { content: project.description } }],
              },
            },
            {
              object: 'block',
              type: 'bulleted_list_item',
              bulleted_list_item: {
                rich_text: [{ text: { content: `Skills: ${project.skills.join(', ')}` } }],
              },
            },
          ],
        },
      });
    }
  }

  // Create the roadmap page
  const page = await notion.pages.create({
    parent: { page_id: parentPage.id },
    properties: {
      title: {
        title: [{ text: { content: `${roleName} - ${new Date().toLocaleDateString()}` } }],
      },
    },
    children: blocks,
  });

  return {
    pageId: page.id,
    url: (page as any).url,
  };
}

// Export interview prep to Notion
export async function exportInterviewPrepToNotion(
  accessToken: string,
  questions: InterviewQuestion[],
  roleName: string,
  difficulty: string
): Promise<ExportResult> {
  const notion = createNotionClient(accessToken);
  
  // Search for existing GapSense Interview Prep page
  const searchResponse = await notion.search({ query: 'GapSense Interview Prep' });
  let parentPage = searchResponse.results.find((result: any) => 
    result.object === 'page' && 
    result.properties?.title?.title?.[0]?.plain_text === 'GapSense Interview Prep'
  ) as any;

  // Create parent page if it doesn't exist
  if (!parentPage) {
    // Use raw axios helper to send { workspace: true } — the SDK types don't include this variant
    parentPage = await notionRequest(accessToken, '/pages', 'POST', {
      parent: { workspace: true },
      properties: {
        title: {
          title: [{ text: { content: 'GapSense Interview Prep' } }],
        },
      },
    });
  }

  // Categorize questions
  const technicalQuestions = questions.filter(q => q.type === 'technical');
  const behavioralQuestions = questions.filter(q => q.type === 'behavioral');
  const systemDesignQuestions = questions.filter(q => q.type === 'system_design');

  // Create blocks for the interview prep content
  const blocks: any[] = [
    {
      object: 'block',
      type: 'heading_1',
      heading_1: {
        rich_text: [{ text: { content: `🎯 ${roleName} - Interview Preparation` } }],
      },
    },
    {
      object: 'block',
      type: 'paragraph',
      paragraph: {
        rich_text: [
          { text: { content: `Difficulty: ${difficulty} | Total Questions: ${questions.length}` } },
        ],
      },
    },
    {
      object: 'block',
      type: 'callout',
      callout: {
        rich_text: [
          { text: { content: '💡 Use this checklist to track your interview preparation progress. Practice answering each question out loud.' } },
        ],
        icon: { emoji: '💡' },
      },
    },
    {
      object: 'block',
      type: 'divider',
      divider: {},
    },
  ];

  // Add technical questions
  if (technicalQuestions.length > 0) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: [{ text: { content: `💻 Technical Questions (${technicalQuestions.length})` } }],
      },
    });

    for (const q of technicalQuestions) {
      blocks.push({
        object: 'block',
        type: 'toggle',
        toggle: {
          rich_text: [{ text: { content: q.question } }],
          children: [
            ...(q.expectedAnswer ? [{
              object: 'block' as const,
              type: 'callout' as const,
              callout: {
                rich_text: [{ text: { content: `Key Points: ${q.expectedAnswer}` } }],
                icon: { emoji: '✅' },
                color: 'green_background' as const,
              },
            }] : []),
            ...(q.hints && q.hints.length > 0 ? [{
              object: 'block' as const,
              type: 'callout' as const,
              callout: {
                rich_text: [
                  { text: { content: 'Hints:\n' } },
                  ...q.hints.map((h: string) => ({ text: { content: `• ${h}\n` } })),
                ],
                icon: { emoji: '💡' },
                color: 'blue_background' as const,
              },
            }] : []),
            {
              object: 'block' as const,
              type: 'to_do' as const,
              to_do: {
                rich_text: [{ text: { content: 'Practiced this question' } }],
                checked: false,
              },
            },
          ],
        },
      });
    }

    blocks.push({
      object: 'block',
      type: 'divider',
      divider: {},
    });
  }

  // Add behavioral questions
  if (behavioralQuestions.length > 0) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: [{ text: { content: `🗣️ Behavioral Questions (${behavioralQuestions.length})` } }],
      },
    });

    for (const q of behavioralQuestions) {
      blocks.push({
        object: 'block',
        type: 'toggle',
        toggle: {
          rich_text: [{ text: { content: q.question } }],
          children: [
            ...(q.expectedAnswer ? [{
              object: 'block' as const,
              type: 'callout' as const,
              callout: {
                rich_text: [{ text: { content: `Approach: ${q.expectedAnswer}` } }],
                icon: { emoji: '✅' },
                color: 'green_background' as const,
              },
            }] : []),
            {
              object: 'block' as const,
              type: 'to_do' as const,
              to_do: {
                rich_text: [{ text: { content: 'Prepared STAR method answer' } }],
                checked: false,
              },
            },
          ],
        },
      });
    }

    blocks.push({
      object: 'block',
      type: 'divider',
      divider: {},
    });
  }

  // Add system design questions
  if (systemDesignQuestions.length > 0) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: [{ text: { content: `🏗️ System Design Questions (${systemDesignQuestions.length})` } }],
      },
    });

    for (const q of systemDesignQuestions) {
      blocks.push({
        object: 'block',
        type: 'toggle',
        toggle: {
          rich_text: [{ text: { content: q.question } }],
          children: [
            ...(q.expectedAnswer ? [{
              object: 'block' as const,
              type: 'callout' as const,
              callout: {
                rich_text: [{ text: { content: `Considerations: ${q.expectedAnswer}` } }],
                icon: { emoji: '✅' },
                color: 'green_background' as const,
              },
            }] : []),
            {
              object: 'block' as const,
              type: 'to_do' as const,
              to_do: {
                rich_text: [{ text: { content: 'Created system design diagram' } }],
                checked: false,
              },
            },
            {
              object: 'block' as const,
              type: 'to_do' as const,
              to_do: {
                rich_text: [{ text: { content: 'Practiced explaining trade-offs' } }],
                checked: false,
              },
            },
          ],
        },
      });
    }
  }

  // Create the interview prep page
  const page = await notion.pages.create({
    parent: { page_id: parentPage.id },
    properties: {
      title: {
        title: [{ text: { content: `${roleName} Interview Prep - ${new Date().toLocaleDateString()}` } }],
      },
    },
    children: blocks,
  });

  return {
    pageId: page.id,
    url: (page as any).url,
  };
}
