import { IGap, IRoadmapMilestone, IProjectSuggestion } from '../models/Assessment';
import SkillOntology from '../models/SkillOntology';
import { gemini, geminiModel } from '../config/gemini';
import { groq, groqProModel } from '../config/groq';

export interface RoadmapInput {
  gaps: IGap[];
  currentSkills: string[];
  targetRole: string;
  durationDays?: number;
  userExperience?: 'entry' | 'mid' | 'senior';
}

export interface GeneratedRoadmap {
  duration: number;
  milestones: IRoadmapMilestone[];
  projectSuggestions: IProjectSuggestion[];
  targetCompletionDate: Date;
  estimatedHours: number;
  weeklyCommitment: string;
}

export async function generateRoadmap(input: RoadmapInput): Promise<GeneratedRoadmap> {
  const { gaps, currentSkills, targetRole, durationDays = 60, userExperience = 'entry' } = input;
  
  if (!gaps || gaps.length === 0) {
    return generateDefaultRoadmap(targetRole, durationDays);
  }

  // 1. RAG - Retrieval: Fetch skill resources from ontology
  const enrichedGaps = await Promise.all(
    gaps.map(async (gap) => {
      const skillOntology = await SkillOntology.findOne({ 
        name: { $regex: new RegExp(gap.skill, 'i') },
        isActive: true 
      });
      return {
        ...gap,
        resources: skillOntology?.resources || [],
        learningPath: skillOntology?.learningPath || [],
        difficulty: skillOntology?.difficulty || 'intermediate',
        description: skillOntology?.description || '',
      };
    })
  );

  const targetCompletionDate = new Date();
  targetCompletionDate.setDate(targetCompletionDate.getDate() + durationDays);
  const weeks = Math.ceil(durationDays / 7);

  // Generate project suggestions (we keep this function as it produces good results)
  const projectSuggestions = await generateProjectSuggestions(
    enrichedGaps, 
    currentSkills, 
    targetRole
  );

  let milestones: IRoadmapMilestone[] = [];
  const hasGemini = !!process.env.GEMINI_API_KEY && gemini && geminiModel;
  const hasGroq = !!process.env.GROQ_API_KEY && groq;

  if (hasGemini || hasGroq) {
    try {
      // 2. RAG - Augmentation: Build prompt with retrieved context
      const prompt = buildRoadmapPrompt(enrichedGaps, currentSkills, targetRole, durationDays, userExperience, weeks);
      
      let content = '';
      let apiFailed = false;

      // 3. RAG - Generation: Try Gemini first
      if (hasGemini) {
        try {
          const result = await geminiModel!.generateContent(prompt);
          const response = await result.response;
          content = response.text();
        } catch (error) {
          console.warn('Gemini roadmap generation failed, trying Groq:', error);
          apiFailed = true;
        }
      }

      // Try Groq if Gemini failed or is unavailable
      if ((!content && hasGroq) || (apiFailed && hasGroq)) {
        try {
          const response = await groq!.chat.completions.create({
            model: groqProModel,
            messages: [
              { role: 'system', content: 'You are an expert technical curriculum designer. Return ONLY a valid JSON array of milestones.' },
              { role: 'user', content: prompt }
            ],
            temperature: 0.7,
            response_format: { type: 'json_object' } // We prompt it to return a wrapped object if needed, but array is expected. Let's just ask for JSON.
          });
          content = response.choices[0]?.message?.content || '';
          apiFailed = false;
        } catch (error) {
          console.warn('Groq roadmap generation also failed:', error);
          apiFailed = true;
        }
      }

      if (content && !apiFailed) {
        milestones = parseLLMResponse(content);
        // Ensure task IDs are present
        milestones.forEach((m, mIdx) => {
          m.week = mIdx + 1;
          m.tasks.forEach((t, tIdx) => {
            t.id = t.id || `w${m.week}-t${tIdx+1}`;
            t.completed = false;
            // Clean up resources
            t.resources = t.resources || [];
          });
        });
      } else {
        throw new Error('All AI API calls failed or returned empty');
      }

    } catch (error) {
      console.error('AI Roadmap Generation Error, falling back to static:', error);
      milestones = generateFallbackMilestones(enrichedGaps, durationDays, userExperience);
    }
  } else {
    // Fallback if no API keys
    milestones = generateFallbackMilestones(enrichedGaps, durationDays, userExperience);
  }

  // Ensure we have exactly the requested number of weeks if generated by AI
  if (milestones.length > weeks) {
    milestones = milestones.slice(0, weeks);
  }

  const estimatedHours = milestones.reduce((total, m) => 
    total + m.tasks.reduce((tTotal, t) => tTotal + (t.estimatedHours || 5), 0), 0
  );

  return {
    duration: durationDays,
    milestones,
    projectSuggestions,
    targetCompletionDate,
    estimatedHours,
    weeklyCommitment: `${Math.max(1, Math.round(estimatedHours / weeks))} hours/week`,
  };
}

function buildRoadmapPrompt(
  gaps: any[], 
  currentSkills: string[], 
  targetRole: string, 
  durationDays: number, 
  userExperience: string,
  weeks: number
): string {
  const gapsContext = gaps.map(g => 
    `- ${g.skill} (Priority: ${g.priority}, Difficulty: ${g.difficulty}): ${g.rationale}. ${g.description ? 'Context: ' + g.description : ''}. Resources available: ${g.resources?.map((r:any) => r.title).join(', ') || 'None'}`
  ).join('\n');

  return `Create a highly detailed, ${weeks}-week technical learning roadmap for a ${userExperience}-level professional targeting a "${targetRole}" role.

The user already knows: ${currentSkills.slice(0, 10).join(', ')}.
They have the following skill gaps to fill:
${gapsContext}

Design a curriculum where each week focuses on a specific "Learning Module" (e.g., "Module: React State Management Architecture" instead of just "Week 1").
CRITICAL: Make tasks highly specific, actionable, and progressive. DO NOT use generic phrases like "Integration Practice" or "Learn Basics". 
Every task must describe a specific implementation, feature to build, or exact concept to master. Ensure it acts as a proper curriculum module.

Format your response strictly as a JSON array of milestones:
\`\`\`json
[
  {
    "title": "Theme of the week (e.g. Master Node.js Fundamentals)",
    "tasks": [
      {
        "title": "Specific task title (e.g. Build an Express middleware)",
        "description": "2-3 sentences explaining exactly what to do and why.",
        "estimatedHours": 5,
        "resources": [
          {
            "title": "Name of tutorial or documentation",
            "url": "https://...",
            "type": "video" // must be "video", "article", "course", or "practice"
          }
        ]
      }
    ]
  }
]
\`\`\`
Ensure there are exactly ${weeks} objects in the array. Provide 3-4 tasks per week. Return ONLY the JSON array, nothing else.`;
}

function parseLLMResponse(content: string): IRoadmapMilestone[] {
  // Extract JSON from response (handle markdown blocks)
  const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/) || [null, content];
  const jsonStr = jsonMatch[1]?.trim() || content.trim();
  
  try {
    const parsed = JSON.parse(jsonStr);
    // Handle cases where Groq might wrap in { milestones: [...] }
    if (parsed.milestones && Array.isArray(parsed.milestones)) {
      return parsed.milestones;
    }
    if (Array.isArray(parsed)) {
      return parsed;
    }
    return [];
  } catch (e) {
    console.error("Failed to parse LLM roadmap JSON:", e);
    throw e;
  }
}

function generateFallbackMilestones(
  enrichedGaps: any[],
  durationDays: number,
  userExperience: string
): IRoadmapMilestone[] {
  const priorityGaps = enrichedGaps.filter(g => g.priority === 'high');
  const mediumGaps = enrichedGaps.filter(g => g.priority === 'medium');
  const lowGaps = enrichedGaps.filter(g => g.priority === 'low');
  
  const weeks = Math.ceil(durationDays / 7);
  const milestones: IRoadmapMilestone[] = [];

  // Week 1-2: Foundation - High Priority Skills
  if (priorityGaps.length > 0) {
    const foundationTasks = priorityGaps.slice(0, 3).flatMap((gap, idx) => [
      {
        id: `w1-t${idx}-1`,
        title: `${gap.skill} Fundamentals`,
        description: gap.learningPath?.[0] || `Learn core concepts of ${gap.skill} through tutorials and documentation`,
        estimatedHours: gap.difficulty === 'beginner' ? 5 : 8,
        resources: gap.resources?.slice(0, 2) || [],
        completed: false,
      },
      {
        id: `w1-t${idx}-2`,
        title: `${gap.skill} Hands-on Practice`,
        description: `Complete practical exercises to reinforce ${gap.skill} concepts. Build a small prototype.`,
        estimatedHours: 4,
        resources: gap.resources?.slice(2, 3) || [],
        completed: false,
      },
    ]);

    milestones.push({
      week: 1,
      title: 'Core Fundamentals & Theory',
      tasks: foundationTasks,
    });

    if (weeks > 1) {
      const week2Tasks = priorityGaps.slice(0, 2).flatMap((gap, idx) => [
        {
          id: `w2-t${idx}-1`,
          title: `Advanced ${gap.skill} Patterns`,
          description: gap.learningPath?.[1] || `Deep dive into advanced ${gap.skill} patterns and best practices. Focus on production readiness.`,
          estimatedHours: 6,
          resources: gap.resources?.slice(1, 3) || [],
          completed: false,
        },
        {
          id: `w2-t${idx}-2`,
          title: `${gap.skill} Mini-Project`,
          description: `Design and implement a targeted project focused entirely on mastering ${gap.skill}.`,
          estimatedHours: 8,
          resources: [],
          completed: false,
        },
      ]);

      milestones.push({
        week: 2,
        title: 'Advanced Applications',
        tasks: week2Tasks,
      });
    }
  }

  // Week 3+: Medium Priority Skills and Integration
  let currentWeek = 3;
  const remainingWeeks = weeks - 2;
  
  if (mediumGaps.length > 0 && remainingWeeks > 0) {
    const mediumWeeks = Math.min(Math.ceil(mediumGaps.length / 2), Math.floor(remainingWeeks * 0.6));
    
    for (let i = 0; i < mediumWeeks && currentWeek <= weeks; i++) {
      const gapsForWeek = mediumGaps.slice(i * 2, i * 2 + 2);
      const tasks = gapsForWeek.flatMap((gap, idx) => [
        {
          id: `w${currentWeek}-t${idx}-1`,
          title: `Mastering ${gap.skill}`,
          description: gap.learningPath?.[0] || `Study essential ${gap.skill} concepts and their use cases in modern stacks.`,
          estimatedHours: gap.difficulty === 'beginner' ? 4 : 6,
          resources: gap.resources?.slice(0, 2) || [],
          completed: false,
        },
        {
          id: `w${currentWeek}-t${idx}-2`,
          title: `${gap.skill} Implementation`,
          description: `Write code integrating ${gap.skill} into an existing codebase or sandbox.`,
          estimatedHours: 4,
          resources: gap.resources?.slice(2, 3) || [],
          completed: false,
        },
      ]);

      milestones.push({
        week: currentWeek,
        title: `Expanding Stack: ${gapsForWeek.map(g => g.skill).join(' & ')}`,
        tasks,
      });
      currentWeek++;
    }
  }

  // Final weeks: Integration and Projects
  while (currentWeek <= weeks) {
    const isLastWeek = currentWeek === weeks;
    const tasks = [
      {
        id: `w${currentWeek}-t1`,
        title: isLastWeek ? 'Capstone Project Launch' : 'Full-Stack Integration',
        description: isLastWeek 
          ? 'Finalize, polish, and deploy your capstone project showcasing your new skills.' 
          : 'Combine multiple newly learned skills into a single integrated architecture.',
        estimatedHours: isLastWeek ? 15 : 10,
        resources: [],
        completed: false,
      },
      {
        id: `w${currentWeek}-t2`,
        title: isLastWeek ? 'Interview Prep & Resume Update' : 'Code Quality & Optimization',
        description: isLastWeek 
          ? 'Update your resume with your new projects and practice technical interview questions related to your gaps.' 
          : 'Refactor your project code. Focus on performance, clean code, and test coverage.',
        estimatedHours: 5,
        resources: [],
        completed: false,
      },
    ];

    if (!isLastWeek && lowGaps.length > 0) {
      const lowGap = lowGaps[(currentWeek - 3) % lowGaps.length];
      tasks.push({
        id: `w${currentWeek}-t3`,
        title: `Introduction to ${lowGap.skill}`,
        description: `Get familiar with ${lowGap.skill} basics. Understand its role in the broader ecosystem.`,
        estimatedHours: 3,
        resources: lowGap.resources?.slice(0, 1) || [],
        completed: false,
      });
    }

    milestones.push({
      week: currentWeek,
      title: isLastWeek ? 'Final Polish & Preparation' : `Integration Phase`,
      tasks,
    });
    currentWeek++;
  }

  return milestones;
}

async function generateProjectSuggestions(
  gaps: any[],
  currentSkills: string[],
  targetRole: string
): Promise<IProjectSuggestion[]> {
  const suggestions: IProjectSuggestion[] = [];
  
  const topGaps = gaps.slice(0, 3).map(g => g.skill);
  
  if (targetRole.toLowerCase().includes('frontend') || targetRole.toLowerCase().includes('fullstack')) {
    suggestions.push({
      title: `${targetRole} Dashboard`,
      description: `Build a comprehensive dashboard showcasing ${topGaps.join(', ')} skills with modern UI/UX practices`,
      technologies: [...currentSkills.slice(0, 4), ...topGaps],
      difficulty: gaps.some(g => g.difficulty === 'advanced') ? 'advanced' : 'intermediate',
      estimatedDays: 14,
      relevance: 'Demonstrates practical application of missing skills in a real-world scenario',
    });
  }

  if (targetRole.toLowerCase().includes('backend') || targetRole.toLowerCase().includes('fullstack')) {
    suggestions.push({
      title: 'RESTful API Service',
      description: `Design and implement a scalable API service using ${topGaps.filter(g => 
        ['Node.js', 'Python', 'Java', 'Go', 'PostgreSQL', 'MongoDB'].some(s => 
          g.toLowerCase().includes(s.toLowerCase())
        )
      ).join(', ') || 'your target stack'}`,
      technologies: [...currentSkills.filter(s => 
        ['Node.js', 'Python', 'PostgreSQL', 'MongoDB', 'Redis', 'Docker'].some(ts => 
          s.toLowerCase().includes(ts.toLowerCase())
        )
      ), ...topGaps].slice(0, 6),
      difficulty: 'intermediate',
      estimatedDays: 10,
      relevance: 'Shows backend architecture understanding and API design skills',
    });
  }

  if (targetRole.toLowerCase().includes('data') || targetRole.toLowerCase().includes('ml')) {
    suggestions.push({
      title: 'Data Analysis Pipeline',
      description: `Create an end-to-end data processing pipeline with visualization using ${topGaps.join(', ')}`,
      technologies: ['Python', 'Pandas', ...topGaps, 'Jupyter Notebook'],
      difficulty: 'advanced',
      estimatedDays: 12,
      relevance: 'Demonstrates data handling and analysis capabilities',
    });
  }

  if (suggestions.length === 0) {
    suggestions.push({
      title: 'Full-Stack Portfolio Project',
      description: `Build a complete application demonstrating ${topGaps.slice(0, 3).join(', ')}`,
      technologies: [...currentSkills.slice(0, 3), ...topGaps.slice(0, 3)],
      difficulty: 'intermediate',
      estimatedDays: 14,
      relevance: 'Comprehensive showcase of both existing and newly acquired skills',
    });
  }

  suggestions.push({
    title: 'Open Source Contribution',
    description: `Find and contribute to an open source project using ${topGaps[0] || 'your target technologies'}`,
    technologies: [...currentSkills.slice(0, 2), ...topGaps.slice(0, 2)],
    difficulty: 'intermediate',
    estimatedDays: 7,
    relevance: 'Shows collaboration skills and real-world code contribution experience',
  });

  return suggestions.slice(0, 3);
}

function generateDefaultRoadmap(targetRole: string, durationDays: number): GeneratedRoadmap {
  const weeks = Math.ceil(durationDays / 7);
  const milestones: IRoadmapMilestone[] = [];

  for (let week = 1; week <= weeks; week++) {
    milestones.push({
      week,
      title: `Week ${week} - Skill Enhancement`,
      tasks: [
        {
          id: `w${week}-t1`,
          title: 'Advanced Concepts Study',
          description: 'Deepen understanding of core technologies',
          estimatedHours: 8,
          resources: [],
          completed: false,
        },
        {
          id: `w${week}-t2`,
          title: 'Code Practice',
          description: 'Solve problems and build small features',
          estimatedHours: 6,
          resources: [],
          completed: false,
        },
      ],
    });
  }

  const targetCompletionDate = new Date();
  targetCompletionDate.setDate(targetCompletionDate.getDate() + durationDays);

  return {
    duration: durationDays,
    milestones,
    projectSuggestions: [{
      title: 'Portfolio Enhancement',
      description: `Build a project showcasing ${targetRole} capabilities`,
      technologies: [],
      difficulty: 'intermediate',
      estimatedDays: 14,
      relevance: 'Demonstrates practical skills to potential employers',
    }],
    targetCompletionDate,
    estimatedHours: weeks * 14,
    weeklyCommitment: '14 hours/week',
  };
}

// Legacy function for backward compatibility
export async function generate60DayRoadmap(missingSkills: string[]) {
  const input: RoadmapInput = {
    gaps: missingSkills.map(skill => ({
      skill,
      currentLevel: 'none',
      requiredLevel: 'intermediate',
      priority: 'high',
      rationale: 'Required skill gap',
    })),
    currentSkills: [],
    targetRole: 'Software Engineer',
    durationDays: 60,
  };

  const roadmap = await generateRoadmap(input);
  
  return {
    weekly_plan: roadmap.milestones.map(m => ({
      week: m.week,
      tasks: m.tasks.map(t => t.title),
    })),
    project_suggestions: roadmap.projectSuggestions.map(p => ({
      title: p.title,
      description: p.description,
    })),
  };
}
