import { IGap, IRoadmapMilestone, IProjectSuggestion } from '../models/Assessment';
import SkillOntology from '../models/SkillOntology';
import { gemini, geminiModel } from '../config/gemini';
import { groq, groqProModel } from '../config/groq';

export interface RoadmapInput {
  gaps: IGap[];
  currentSkills: string[];
  targetRole: string;
  durationDays?: number;
  userExperience?: 'entry' | 'mid' | 'senior';
}

export interface GeneratedRoadmap {
  duration: number;
  milestones: IRoadmapMilestone[];
  projectSuggestions: IProjectSuggestion[];
  targetCompletionDate: Date;
  estimatedHours: number;
  weeklyCommitment: string;
}

export async function generateRoadmap(input: RoadmapInput): Promise<GeneratedRoadmap> {
  const { gaps, currentSkills, targetRole, durationDays = 60, userExperience = 'entry' } = input;
  
  if (!gaps || gaps.length === 0) {
    return generateDefaultRoadmap(targetRole, durationDays);
  }

  // 1. RAG - Retrieval: Fetch skill resources from ontology
  const enrichedGaps = await Promise.all(
    gaps.map(async (gap) => {
      const skillOntology = await SkillOntology.findOne({ 
        name: { $regex: new RegExp(gap.skill, 'i') },
        isActive: true 
      });
      return {
        ...gap,
        resources: skillOntology?.resources || [],
        learningPath: skillOntology?.learningPath || [],
        difficulty: skillOntology?.difficulty || 'intermediate',
        description: skillOntology?.description || '',
      };
    })
  );

  const targetCompletionDate = new Date();
  targetCompletionDate.setDate(targetCompletionDate.getDate() + durationDays);
  const weeks = Math.ceil(durationDays / 7);

  let milestones: IRoadmapMilestone[] = [];
  let projectSuggestions: IProjectSuggestion[] = [];
  
  const hasGemini = !!process.env.GEMINI_API_KEY && gemini && geminiModel;
  const hasGroq = !!process.env.GROQ_API_KEY && groq;

  if (hasGemini || hasGroq) {
    try {
      // 2. RAG - Augmentation: Build prompt with retrieved context
      const prompt = buildRoadmapPrompt(enrichedGaps, currentSkills, targetRole, durationDays, userExperience, weeks);
      
      let content = '';
      let apiFailed = false;

      // 3. RAG - Generation: Try Gemini first
      if (hasGemini) {
        try {
          const result = await geminiModel!.generateContent(prompt);
          const response = await result.response;
          content = response.text();
        } catch (error) {
          console.warn('Gemini roadmap generation failed, trying Groq:', error);
          apiFailed = true;
        }
      }

      // Try Groq if Gemini failed or is unavailable
      if ((!content && hasGroq) || (apiFailed && hasGroq)) {
        try {
          const response = await groq!.chat.completions.create({
            model: groqProModel,
            messages: [
              { role: 'system', content: 'You are an expert technical curriculum designer. Return ONLY a valid JSON object.' },
              { role: 'user', content: prompt }
            ],
            temperature: 0.7,
            response_format: { type: 'json_object' }
          });
          content = response.choices[0]?.message?.content || '';
          apiFailed = false;
        } catch (error) {
          console.warn('Groq roadmap generation also failed:', error);
          apiFailed = true;
        }
      }

      if (content && !apiFailed) {
        const parsed = parseLLMResponse(content);
        milestones = parsed.milestones;
        projectSuggestions = parsed.projectSuggestions || [];
        
        // Ensure task IDs are present
        milestones.forEach((m, mIdx) => {
          m.week = mIdx + 1;
          m.tasks.forEach((t, tIdx) => {
            t.id = t.id || `w${m.week}-t${tIdx+1}`;
            t.completed = false;
            // Clean up resources
            t.resources = t.resources || [];
          });
        });
      } else {
        throw new Error('All AI API calls failed or returned empty');
      }

    } catch (error) {
      milestones = generateFallbackMilestones(enrichedGaps, durationDays, userExperience, targetRole);
    }
  } else {
    // Fallback if no API keys
    milestones = generateFallbackMilestones(enrichedGaps, durationDays, userExperience, targetRole);
  }


  // If project suggestions are still empty (AI failed or was skipped), generate fallback ones
  if (projectSuggestions.length === 0) {
    projectSuggestions = await generateProjectSuggestions(
      enrichedGaps, 
      currentSkills, 
      targetRole
    );
  }

  // Ensure we have exactly the requested number of weeks if generated by AI
  if (milestones.length > weeks) {
    milestones = milestones.slice(0, weeks);
  }

  const estimatedHours = milestones.reduce((total, m) => 
    total + m.tasks.reduce((tTotal, t) => tTotal + (t.estimatedHours || 5), 0), 0
  );

  return {
    duration: durationDays,
    milestones,
    projectSuggestions,
    targetCompletionDate,
    estimatedHours,
    weeklyCommitment: `${Math.max(1, Math.round(estimatedHours / weeks))} hours/week`,
  };
}


function buildRoadmapPrompt(
  gaps: any[], 
  currentSkills: string[], 
  targetRole: string, 
  durationDays: number, 
  userExperience: string,
  weeks: number
): string {
  const gapsContext = gaps.map(g => 
    `- ${g.skill} (Priority: ${g.priority}, Difficulty: ${g.difficulty}): ${g.rationale}. ${g.description ? 'Context: ' + g.description : ''}. Resources available: ${g.resources?.map((r:any) => r.title).join(', ') || 'None'}`
  ).join('\n');

  return `Create a highly detailed, ${weeks}-week technical learning roadmap and 2-3 tailored project suggestions for a ${userExperience}-level professional targeting a "${targetRole}" role.

The user already knows: ${currentSkills.slice(0, 10).join(', ')}.
They have the following skill gaps to fill:
${gapsContext}

Design a curriculum where each week focuses on a specific "Learning Module" (e.g., "Module: React State Management Architecture" instead of just "Week 1").
CRITICAL: Make tasks highly specific, actionable, and progressive. Every task must describe a specific implementation, feature to build, or exact concept to master.

Also, suggest 2-3 specific, portfolio-worthy projects that would demonstrate mastery of the missing skills for this EXACT role ("${targetRole}"). 
Avoid generic tech projects if the role is non-traditional (e.g., suggest a "Crop Yield Prediction Tool" for a Farmer or a "Multi-Channel Content Scheduler" for a Social Media Manager).

Format your response strictly as a JSON object:
\`\`\`json
{
  "milestones": [
    {
      "title": "Theme of the week",
      "tasks": [
        {
          "title": "Specific task title",
          "description": "2-3 sentences explaining exactly what to do.",
          "estimatedHours": 5,
          "resources": [
            {
              "title": "Resource Name",
              "url": "https://...",
              "type": "video" 
            }
          ]
        }
      ]
    }
  ],
  "projectSuggestions": [
    {
      "title": "Specific Project Title",
      "description": "Detailed description showing how it uses the missing skills.",
      "technologies": ["Tech 1", "Tech 2"],
      "difficulty": "intermediate",
      "estimatedDays": 10,
      "relevance": "Why this project is crucial for a ${targetRole}."
    }
  ]
}
\`\`\`
Ensure there are exactly ${weeks} milestones. Provide 3-4 tasks per week. Return ONLY the JSON object.`;
}

function parseLLMResponse(content: string): { milestones: IRoadmapMilestone[], projectSuggestions?: IProjectSuggestion[] } {
  // Extract JSON from response (handle markdown blocks)
  const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/) || [null, content];
  const jsonStr = jsonMatch[1]?.trim() || content.trim();
  
  try {
    const parsed = JSON.parse(jsonStr);
    
    // Handle the new object structure { milestones, projectSuggestions }
    if (parsed.milestones && Array.isArray(parsed.milestones)) {
      return {
        milestones: parsed.milestones,
        projectSuggestions: Array.isArray(parsed.projectSuggestions) ? parsed.projectSuggestions : []
      };
    }
    
    // Fallback for old array-only response
    if (Array.isArray(parsed)) {
      return { milestones: parsed };
    }
    
    return { milestones: [] };
  } catch (e) {
    console.error("Failed to parse LLM roadmap JSON:", e);
    throw e;
  }
}


function generateFallbackMilestones(
  enrichedGaps: any[],
  durationDays: number,
  userExperience: string,
  targetRole: string
): IRoadmapMilestone[] {

  const priorityGaps = enrichedGaps.filter(g => g.priority === 'high');
  const mediumGaps = enrichedGaps.filter(g => g.priority === 'medium');
  const lowGaps = enrichedGaps.filter(g => g.priority === 'low');
  
  const weeks = Math.ceil(durationDays / 7);
  const milestones: IRoadmapMilestone[] = [];

  // Week 1-2: Foundation - High Priority Skills
  if (priorityGaps.length > 0) {
    const foundationTasks = priorityGaps.slice(0, 3).flatMap((gap, idx) => [
      {
        id: `w1-t${idx}-1`,
        title: `${gap.skill} Fundamentals`,
        description: gap.learningPath?.[0] || `Learn core concepts of ${gap.skill} through tutorials and documentation`,
        estimatedHours: gap.difficulty === 'beginner' ? 5 : 8,
        resources: gap.resources?.slice(0, 2) || [],
        completed: false,
      },
      {
        id: `w1-t${idx}-2`,
        title: `${gap.skill} Hands-on Practice`,
        description: `Complete practical exercises to reinforce ${gap.skill} concepts. Build a small prototype.`,
        estimatedHours: 4,
        resources: gap.resources?.slice(2, 3) || [],
        completed: false,
      },
    ]);

    milestones.push({
      week: 1,
      title: `${targetRole} Foundation & Theory`,
      tasks: foundationTasks,
    });


    if (weeks > 1) {
      const week2Tasks = priorityGaps.slice(0, 2).flatMap((gap, idx) => [
        {
          id: `w2-t${idx}-1`,
          title: `Advanced ${gap.skill} Patterns`,
          description: gap.learningPath?.[1] || `Deep dive into advanced ${gap.skill} patterns and best practices. Focus on production readiness.`,
          estimatedHours: 6,
          resources: gap.resources?.slice(1, 3) || [],
          completed: false,
        },
        {
          id: `w2-t${idx}-2`,
          title: `${gap.skill} Mini-Project`,
          description: `Design and implement a targeted project focused entirely on mastering ${gap.skill}.`,
          estimatedHours: 8,
          resources: [],
          completed: false,
        },
      ]);

      milestones.push({
        week: 2,
        title: `Advanced ${targetRole} Applications`,
        tasks: week2Tasks,
      });

    }
  }

  // Week 3+: Medium Priority Skills and Integration
  let currentWeek = 3;
  const remainingWeeks = weeks - 2;
  
  if (mediumGaps.length > 0 && remainingWeeks > 0) {
    const mediumWeeks = Math.min(Math.ceil(mediumGaps.length / 2), Math.floor(remainingWeeks * 0.6));
    
    for (let i = 0; i < mediumWeeks && currentWeek <= weeks; i++) {
      const gapsForWeek = mediumGaps.slice(i * 2, i * 2 + 2);
      const tasks = gapsForWeek.flatMap((gap, idx) => [
        {
          id: `w${currentWeek}-t${idx}-1`,
          title: `Mastering ${gap.skill}`,
          description: gap.learningPath?.[0] || `Study essential ${gap.skill} concepts and their use cases in modern stacks.`,
          estimatedHours: gap.difficulty === 'beginner' ? 4 : 6,
          resources: gap.resources?.slice(0, 2) || [],
          completed: false,
        },
        {
          id: `w${currentWeek}-t${idx}-2`,
          title: `${gap.skill} Implementation`,
          description: `Write code integrating ${gap.skill} into an existing codebase or sandbox.`,
          estimatedHours: 4,
          resources: gap.resources?.slice(2, 3) || [],
          completed: false,
        },
      ]);

      milestones.push({
        week: currentWeek,
        title: `Expanding Stack: ${gapsForWeek.map(g => g.skill).join(' & ')}`,
        tasks,
      });
      currentWeek++;
    }
  }

  // Final weeks: Integration and Projects
  while (currentWeek <= weeks) {
    const isLastWeek = currentWeek === weeks;
    const tasks = [
      {
        id: `w${currentWeek}-t1`,
        title: isLastWeek ? 'Capstone Project Launch' : 'Full-Stack Integration',
        description: isLastWeek 
          ? 'Finalize, polish, and deploy your capstone project showcasing your new skills.' 
          : 'Combine multiple newly learned skills into a single integrated architecture.',
        estimatedHours: isLastWeek ? 15 : 10,
        resources: [],
        completed: false,
      },
      {
        id: `w${currentWeek}-t2`,
        title: isLastWeek ? 'Interview Prep & Resume Update' : 'Code Quality & Optimization',
        description: isLastWeek 
          ? 'Update your resume with your new projects and practice technical interview questions related to your gaps.' 
          : 'Refactor your project code. Focus on performance, clean code, and test coverage.',
        estimatedHours: 5,
        resources: [],
        completed: false,
      },
    ];

    if (!isLastWeek && lowGaps.length > 0) {
      const lowGap = lowGaps[(currentWeek - 3) % lowGaps.length];
      tasks.push({
        id: `w${currentWeek}-t3`,
        title: `Introduction to ${lowGap.skill}`,
        description: `Get familiar with ${lowGap.skill} basics. Understand its role in the broader ecosystem.`,
        estimatedHours: 3,
        resources: lowGap.resources?.slice(0, 1) || [],
        completed: false,
      });
    }

    milestones.push({
      week: currentWeek,
      title: isLastWeek ? 'Final Polish & Preparation' : `Integration Phase`,
      tasks,
    });
    currentWeek++;
  }

  return milestones;
}

async function generateProjectSuggestions(
  gaps: any[],
  currentSkills: string[],
  targetRole: string
): Promise<IProjectSuggestion[]> {
  const suggestions: IProjectSuggestion[] = [];
  
  const topGaps = gaps.slice(0, 3).map(g => g.skill);
  const roleLower = targetRole.toLowerCase();
  
  const isTechRole = roleLower.includes('frontend') || 
                     roleLower.includes('fullstack') || 
                     roleLower.includes('backend') || 
                     roleLower.includes('developer') || 
                     roleLower.includes('software') || 
                     roleLower.includes('web');

  if (isTechRole) {

    if (roleLower.includes('frontend') || roleLower.includes('fullstack')) {
      suggestions.push({
        title: `${targetRole} Portfolio Dashboard`,
        description: `Build a comprehensive dashboard showcasing ${topGaps.join(', ')} skills with modern UI/UX practices tailored for a ${targetRole} role.`,
        technologies: [...currentSkills.slice(0, 4), ...topGaps],
        difficulty: gaps.some(g => g.difficulty === 'advanced') ? 'advanced' : 'intermediate',
        estimatedDays: 14,
        relevance: 'Demonstrates practical application of missing skills in a real-world scenario.',
      });
    }

    if (roleLower.includes('backend') || roleLower.includes('fullstack')) {
      suggestions.push({
        title: `${targetRole} API Infrastructure`,
        description: `Design and implement a scalable backend service using ${topGaps.filter(g => 
          ['Node.js', 'Python', 'Java', 'Go', 'PostgreSQL', 'MongoDB'].some(s => 
            g.toLowerCase().includes(s.toLowerCase())
          )
        ).join(', ') || 'your target stack'} to solve role-specific data challenges.`,
        technologies: [...currentSkills.filter(s => 
          ['Node.js', 'Python', 'PostgreSQL', 'MongoDB', 'Redis', 'Docker'].some(ts => 
            s.toLowerCase().includes(ts.toLowerCase())
          )
        ), ...topGaps].slice(0, 6),
        difficulty: 'intermediate',
        estimatedDays: 10,
        relevance: `Shows architecture understanding and API design skills relevant to ${targetRole}.`,
      });
    }
  }


  // List of roles that typically don't require a portfolio of projects
  const nonProjectRoles = ['manager', 'director', 'executive', 'hr', 'recruiter', 'sales', 'support', 'customer success'];
  const isNonProjectRole = nonProjectRoles.some(r => roleLower.includes(r));

  // Generic but better fallback for non-tech roles
  if (suggestions.length === 0 && !isNonProjectRole) {
    suggestions.push({
      title: `${targetRole} Capstone Project`,
      description: `Create a comprehensive project that applies ${topGaps.slice(0, 3).join(', ')} to solve a core problem faced by a ${targetRole}. This should demonstrate your ability to deliver end-to-end value in this role.`,
      technologies: [...currentSkills.slice(0, 3), ...topGaps.slice(0, 3)],
      difficulty: 'intermediate',
      estimatedDays: 14,
      relevance: `Demonstrates how your new skills directly impact your performance as a ${targetRole}.`,
    });
  }

  if (roleLower.includes('data') || roleLower.includes('ml') || roleLower.includes('analyst')) {
    suggestions.push({
      title: `${targetRole} Insight Pipeline`,
      description: `Create an end-to-end data processing and visualization pipeline using ${topGaps.join(', ')} focused on ${targetRole} metrics.`,
      technologies: ['Python', 'Pandas', ...topGaps, 'Jupyter Notebook'],
      difficulty: 'advanced',
      estimatedDays: 12,
      relevance: `Demonstrates data handling and analysis capabilities specific to this role.`,
    });
  }

  // Only add community contribution if relevant or if it's a tech role
  if (isTechRole || !isNonProjectRole) {
    suggestions.push({
      title: `${targetRole} Community Contribution`,
      description: `Find and contribute to a project, tool, or industry discussion used in the ${targetRole} ecosystem using ${topGaps[0] || 'your target skills'}.`,
      technologies: [...currentSkills.slice(0, 2), ...topGaps.slice(0, 2)],
      difficulty: 'intermediate',
      estimatedDays: 7,
      relevance: `Shows collaboration skills and real-world contribution experience in the ${targetRole} field.`,
    });
  }

  return suggestions.slice(0, 3);
}



function generateDefaultRoadmap(targetRole: string, durationDays: number): GeneratedRoadmap {
  const weeks = Math.ceil(durationDays / 7);
  const milestones: IRoadmapMilestone[] = [];

  for (let week = 1; week <= weeks; week++) {
    milestones.push({
      week,
      title: `Week ${week} - Skill Enhancement`,
      tasks: [
        {
          id: `w${week}-t1`,
          title: 'Advanced Concepts Study',
          description: 'Deepen understanding of core technologies',
          estimatedHours: 8,
          resources: [],
          completed: false,
        },
        {
          id: `w${week}-t2`,
          title: 'Code Practice',
          description: 'Solve problems and build small features',
          estimatedHours: 6,
          resources: [],
          completed: false,
        },
      ],
    });
  }

  const targetCompletionDate = new Date();
  targetCompletionDate.setDate(targetCompletionDate.getDate() + durationDays);

  return {
    duration: durationDays,
    milestones,
    projectSuggestions: [{
      title: 'Portfolio Enhancement',
      description: `Build a project showcasing ${targetRole} capabilities`,
      technologies: [],
      difficulty: 'intermediate',
      estimatedDays: 14,
      relevance: 'Demonstrates practical skills to potential employers',
    }],
    targetCompletionDate,
    estimatedHours: weeks * 14,
    weeklyCommitment: '14 hours/week',
  };
}

// Legacy function for backward compatibility
export async function generate60DayRoadmap(missingSkills: string[]) {
  const input: RoadmapInput = {
    gaps: missingSkills.map(skill => ({
      skill,
      currentLevel: 'none',
      requiredLevel: 'intermediate',
      priority: 'high',
      rationale: 'Required skill gap',
    })),
    currentSkills: [],
    targetRole: 'Software Engineer',
    durationDays: 60,
  };

  const roadmap = await generateRoadmap(input);
  
  return {
    weekly_plan: roadmap.milestones.map(m => ({
      week: m.week,
      tasks: m.tasks.map(t => t.title),
    })),
    project_suggestions: roadmap.projectSuggestions.map(p => ({
      title: p.title,
      description: p.description,
    })),
  };
}
